### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by atherdon** [atherdon/publish-page#9]
- add gulp to the repository and discuss how to scale it.

Наша цель в том, чтобы иметь возможность быстро и легко изменять:

### SEO tags: keywords, meta, etc.
![image](https://user-images.githubusercontent.com/1469198/103305825-d3507980-4a14-11eb-9609-2d3021249aa1.png)

### heading/subheading

![image](https://user-images.githubusercontent.com/1469198/103305871-ebc09400-4a14-11eb-900a-a502576405c3.png)

### section with top articles 
 нужно ли нам делать какой то определенный size для картинок и т.д. есть ли какие то ограничения по этой секции

![image](https://user-images.githubusercontent.com/1469198/103305897-fbd87380-4a14-11eb-8b6a-56e3595077f4.png)

я думаю что нам нужно в какой то момент сделать 2 папки. в одной будет хранится publish-page-template-latest-version, а в другой папке будут хранится страницы, которые мы будем выкладывать по типам.

**Comment by F1reMonster** [comment]
> section with top articles

для картинок не потрібно робити якийсь розмір, вони самі підлаштовуються, тут вони всі різні із різними параметрами

**Comment by atherdon** [comment]
> > section with top articles
> 
> для картинок не потрібно робити якийсь розмір, вони самі підлаштовуються, тут вони всі різні із різними параметрами

я просто думал - для оптимизации скорости работы - мы можем взять какой то размер - и все картинки пережимать

**Comment by atherdon** [comment]
мне кажется что мы закончили этот таск
